### ISSUE TITLE
Target elements already styled with body_class

### ISSUE THREAD

**Issue by JiveDig** [stylesplugin/styles#55]
I'm working on a Styles add-on for a theme that has home page specific styling... like this:

.home .entry-title {}

When using .home .entry-title in the JSON file, it won't work as expected since .styles is also a body class. Is there a workaround for this issue?  My styles can't effect other pages either, since this is a home specific style.

Thanks!

**Comment by pdclark** [comment]
Sorry — not possible as far as I know with the current setup. .styles would need to be moved to `<html>`

**Comment by pdclark** [comment]
Never mind. I think this is possible. Try starting your selector with `body.home` or `html .home`

Note there is a space after `html`, but no space after `body`.

**Comment by JiveDig** [comment]
I can't get this to work at all. It doesn't seem to matter which I use, because .styles IS the body class... so everything breaks if I add another body.classname in the JSON file.
